#!/usr/bin/env node
'use strict';
// Generate the Stuff audit workbook from the current radar.json with no third-party package.
// The 0–100 score comes from source_merit.js, so browser preview and workbook stay aligned.
const fs=require('fs');
const path=require('path');
const Merit=require('../source_merit.js');
const ROOT=path.resolve(__dirname,'..');
const data=JSON.parse(fs.readFileSync(path.join(ROOT,'radar.json'),'utf8'));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const titleOf=x=>clean(x.title||x.headline);
const linkOf=x=>clean(x.link||x.url);
const products=[['A',data.strand_a],['B',data.strand_b],['C',data.strand_c],['Matrix evidence',data.frontier_evidence],['Strategic pathway',data.strategic_pathways]];
const groups=new Map();
for(const [product,items] of products){for(const x of Array.isArray(items)?items:[]){if(!x||typeof x!=='object')continue;const u=linkOf(x).toLowerCase().replace(/\/$/,'');const t=norm(titleOf(x));const key=u?'u:'+u:'t:'+t;if(key==='t:')continue;const comp=[x.summary,x.core_message,x.relevance_note,x.why_it_matters,x.authors,x.source,x.link].filter(v=>clean(v)).length;const score=Merit.scoreFor(x);const old=groups.get(key);if(!old)groups.set(key,{x,products:new Set([product]),score,comp});else{old.products.add(product);if(score>old.score||(score===old.score&&comp>old.comp)){old.x=x;old.score=score;old.comp=comp}}}}
const rows=[...groups.values()].map(g=>{const x=g.x,m=Merit.forItem(x),c=Merit.componentsFor(x),sc=x.strategic_classification&&typeof x.strategic_classification==='object'?clean(x.strategic_classification.primary):'';return {score:m.score,band:`${m.code} — ${m.label}`,title:titleOf(x),date:clean(x.date).slice(0,10),product:[...g.products].sort().join(', '),source:clean(x.source||x.journal||x.institution),authors:clean(x.authors),authorityPoints:c.authorityPoints,authority:c.authority,relevancePoints:c.relevancePoints,relevance:c.relevance,evidencePoints:c.evidencePoints,evidence:c.evidence,authorPoints:c.authorTransparencyPoints,type:clean(x.type||x.signal_kind),euRelevance:clean(x.eu_relevance||x.euRelevance),euEvidence:(x.eu_evidence||[]).map(clean).join('; '),riEvidence:(x.ri_evidence||[]).map(clean).join('; '),geoEvidence:(x.geo_evidence||[]).map(clean).join('; '),core:clean(x.core_message||x.signal_note||x.summary),note:clean(x.relevance_note||x.why_it_matters),matrix:clean(x.matrix_auto_cell),strategic:sc,provenance:clean(x.discovery_provenance||x.origin),sourceTier:clean(x.source_tier||x.sourceTier),firstSeen:clean(x.first_seen),link:linkOf(x)}}).sort((a,b)=>b.score-a.score||b.date.localeCompare(a.date)||a.title.localeCompare(b.title));
rows.forEach((r,i)=>r.rank=i+1);

const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const col=n=>{let s='';for(;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s};
function cell(v,r,c,style=0){const ref=col(c)+r;if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}" s="${style}"><v>${v}</v></c>`;return `<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`}
function sheetXml(headers, body, widths){const maxc=headers.length;let xml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>`;xml+=`<row r="1" ht="28" customHeight="1">${headers.map((h,i)=>cell(h,1,i+1,1)).join('')}</row>`;for(let i=0;i<body.length;i++){xml+=`<row r="${i+2}">${body[i].map((v,j)=>cell(v,i+2,j+1,j===1?2:3)).join('')}</row>`}xml+=`</sheetData><autoFilter ref="A1:${col(maxc)}${body.length+1}"/></worksheet>`;return xml}
const h1=['Rank','Score / 100','Band','Title','Date','Product','Source','Authors','Authority / 55','Authority basis','EU relevance / 25','EU relevance basis','Evidence / 15','Evidence basis','Author transparency / 5','Type','EU relevance code','EU evidence','R&I evidence','Strategic evidence','Core message','Relevance / admission note','Matrix auto cell','Strategic classification','Discovery provenance','Source tier','First seen','Source link'];
const b1=rows.map(r=>[r.rank,r.score,r.band,r.title,r.date,r.product,r.source,r.authors,r.authorityPoints,r.authority,r.relevancePoints,r.relevance,r.evidencePoints,r.evidence,r.authorPoints,r.type,r.euRelevance,r.euEvidence,r.riEvidence,r.geoEvidence,r.core,r.note,r.matrix,r.strategic,r.provenance,r.sourceTier,r.firstSeen,r.link]);
const widths=[8,11,16,42,12,16,27,32,12,28,15,31,12,28,18,24,18,28,28,28,42,48,20,22,24,20,20,42];
const method=[['TECHNICAL EVIDENCE RANKING — HOW TO READ IT',''],['Purpose','Audit/export ranking for evidence used by the EU R&I × geopolitics radar. It is intentionally confined to Stuff.'],['Score','0–100 = source authority + EU relevance + evidence strength + author transparency.'],['Authority (max 55)','EU official/body 55; major public/multilateral 48; strong science network or leading peer-reviewed journal 46; leading policy institute 43; established journal/publisher 38; ordinary peer-reviewed journal 32; specialist/current-event source about 25–27; preprint 22.'],['EU relevance (max 25)','Direct EU relevance 25; material external development with EU implications 20; relevance by comparison/implication 18. EU relevance is also enforced separately by scanner admission logic for substantive evidence products.'],['Evidence (max 15)','Official or peer-reviewed source 15; institutional/manual-verified research 13–14; current-event signal 9; preprint or abstract 8.'],['Author transparency (max 5)','Named author(s) 5; identifiable institutional author 4; no named author in radar metadata 2.'],['Bands','A ≥93 Highest; B 85–92 Very strong; C 75–84 Strong; D 65–74 Useful; E <65 Supporting.'],['Scanner role','The 0–100 score itself does not admit or reject findings. Scanner admission separately requires acceptable source provenance and EU/R&I scope.'],['Reader-ordering rule','The score must not order Radar, Matrix, Literature, Risks & Opportunities, External Shocks, issue views or Historical evidence.'],['Matrix rule','Source quality and this score do not determine Matrix placement. Matrix is a separate analytical product.'],['Strategic-products rule','Risks, Opportunities and External Shocks are independently scanned and classified from source text; this score is audit metadata only.'],['Current data state',`${clean(data.run_completed_at||data.last_updated)} · A=${(data.strand_a||[]).length} · B=${(data.strand_b||[]).length} · C=${(data.strand_c||[]).length} · Strategic pathways=${(data.strategic_pathways||[]).length}`],['Workbook rows',`${rows.length} deduplicated evidence records`]];
const s1=sheetXml(h1,b1,widths);const s2=sheetXml(['Field','Explanation'],method,[28,95]);
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFC40018"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF111111"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment wrapText="1" vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
const files={
'[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`,
'_rels/.rels':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Ranked sources" sheetId="1" r:id="rId1"/><sheet name="Method" sheetId="2" r:id="rId2"/></sheets></workbook>`,
'xl/_rels/workbook.xml.rels':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
'xl/styles.xml':styles,'xl/worksheets/sheet1.xml':s1,'xl/worksheets/sheet2.xml':s2};
let crcTable=null;function crc32(buf){if(!crcTable){crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;return c>>>0})}let c=0xFFFFFFFF;for(const b of buf)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xFFFFFFFF)>>>0}
function zip(entries){const locals=[],centrals=[];let offset=0;const date=33,time=0,flag=0x800;for(const [name,text] of Object.entries(entries)){const nb=Buffer.from(name,'utf8'),db=Buffer.from(text,'utf8'),crc=crc32(db);const lh=Buffer.alloc(30);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt16LE(flag,6);lh.writeUInt16LE(0,8);lh.writeUInt16LE(time,10);lh.writeUInt16LE(date,12);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(db.length,18);lh.writeUInt32LE(db.length,22);lh.writeUInt16LE(nb.length,26);lh.writeUInt16LE(0,28);locals.push(lh,nb,db);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt16LE(flag,8);ch.writeUInt16LE(0,10);ch.writeUInt16LE(time,12);ch.writeUInt16LE(date,14);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(db.length,20);ch.writeUInt32LE(db.length,24);ch.writeUInt16LE(nb.length,28);ch.writeUInt16LE(0,30);ch.writeUInt16LE(0,32);ch.writeUInt16LE(0,34);ch.writeUInt16LE(0,36);ch.writeUInt32LE(0,38);ch.writeUInt32LE(offset,42);centrals.push(ch,nb);offset+=lh.length+nb.length+db.length}const central=Buffer.concat(centrals),local=Buffer.concat(locals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(Object.keys(entries).length,8);end.writeUInt16LE(Object.keys(entries).length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(local.length,16);end.writeUInt16LE(0,20);return Buffer.concat([local,central,end])}
const out=path.join(ROOT,'stuff','source_merit_ranking.xlsx');fs.writeFileSync(out,zip(files));console.log(`Wrote ${out}: ${rows.length} ranked records`);
